config/routes.rb
Cancandemo::Application.routes.draw do
  devise_for :users

  resources :posts

  root :to => "posts#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :find_post, :only => [:edit, :update, :show, :destroy]
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(params[:post])
    if @post.save
      redirect_to posts_path
    else
      render :action => "new"
    end
  end
  
  def edit
  end
  
  def update
    if @post.update_attributes(params[:post])
      redirect_to post_path(@post)
    else
      render :action => "edit"
    end
  end
  
  def show

  end
  
  def destroy
    @post.destroy
    redirect_to posts_path
  end
  
  protected
  
  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cancandemo</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post, :url => post_path(@post), :method => :put do |f| %>
    <%= f.label :subject, "Subject" %>
    <%= f.text_field :subject %>
    <%= f.text_area :content %>
    <%= f.submit "Create" %>
<% end %>

app/views/posts/index.html.erb
<ul>
    <% @posts.each do |post| %>
        <li>
            <%= link_to(post.subject, post_path(post)) %>
            <%= link_to("Edit", edit_post_path(post)) %>
            <%= link_to("Destroy", post_path(post), :method => :delete)%>
        </li>
    <% end %>
</ul>

<%= link_to("New Post", new_post_path) %>

app/views/posts/new.html.erb
<%= form_for @post, :url => posts_path(@post) do |f| %>
    <%= f.label :subject, "Subject" %>
    <%= f.text_field :subject %>
    <%= f.text_area :content %>
    <%= f.submit "Create" %>
<% end %>

app/views/posts/show.html.erb
<ul>
    <li><%= @post.subject %></li>
    <li><%= simple_format(@post.content) %></li>
    <li><%= link_to("Home", root_path) %></li>
</ul>